services:

  g-agent:
    profiles:
      - minimal
      - default
      - full
    restart: unless-stopped
    image: g-agent:1.0
    container_name: g-agent
    hostname: g-agent
    environment:
      NODE_ENV: production
      PORT: 6677
      HOST: 0.0.0.0
      LLM_URL: https://logus2k.com/llm
      STT_URL: https://logus2k.com/stt
      TTS_URL: https://logus2k.com/tts    
    ports:
      - "6677:6677"
    networks:
      - logus2k_network

networks:
  logus2k_network:
    external: true
